[algokit]
min_version = "v2.0.0"

[project]
type = 'contract'
name = 'cred_contracts'

[project.run]
build = { commands = ['poetry install', 'poetry run python -m src.deploy_localnet --compile'], description = 'Build smart contracts' }
test = { commands = ['poetry run pytest'], description = 'Run tests' }
lint = { commands = ['poetry run ruff .', 'poetry run black --check .'], description = 'Run linting' }
deploy_localnet = { commands = ['poetry run python -m src.deploy_localnet --deploy'], description = 'Deploy to LocalNet' }

[project.deploy]
command = "poetry run python -m src.deploy_localnet --deploy"
environment_secrets = ["DEPLOYER_MNEMONIC"]

[project.env]
NEXT_PUBLIC_APP_ID = "1005"
NEXT_PUBLIC_ADMIN_ADDRESS = "KYK6GIIY7JXHCX2VOQF2PFZJH4B5EL5KHCJ7CFSF7K7TZKONGWPUBA6OSM"