[algokit]
min_version = "v2.0.0"

[project]
type = 'workspace'
projects_root_path = 'projects'

[project.run]
build = ['cred_contracts', 'web']
lint = ['cred_contracts', 'web']
test = ['cred_contracts']
deploy_localnet = ['cred_contracts']